### ISSUE TITLE
enumerator.reverse with ruby 1.9.3

### ISSUE THREAD

**Issue by dkmdnielsen** [woahdae/simple_xlsx_reader#19]
I have a ruby 1.9.3 (windows) install.  This gem errors out in the following method:

```ruby
      def column_letter_to_number(column_letter)
        pow = -1
        column_letter.codepoints.reverse.inject(0) do |acc, charcode|
          pow += 1
          acc + 26**pow * (charcode - 64)
        end
      end
```

For 1.9.3, the iterator needs to have to_a, as in `column_letter.codepoints.to_a.reverse.inject(0)`.  Once that is in place, all is good with the tests.

If simple_xlsx_reader is meant for ruby 2+, then I didn't get that from any dependencies.  Sorry.

**Comment by woahdae** [comment]
Fixed by @eritiro in #20
