### ISSUE TITLE
Percentage 100 times too small

### ISSUE THREAD

**Issue by neuronwave** [woahdae/simple_xlsx_reader#21]
Using the linked to XLSX, generated in Excel for Mac, the percentages are being cast as 100 times too small. 

http://flmisc.s3.amazonaws.com/multiple_field_type.xlsx

The result is 
 = #SimpleXlsxReader::Document:0x000001012a55d8 @file_path="Dropbox/clients/oslo_data/multiple_field_type.xlsx", @sheets=[#struct SimpleXlsxReader::Document::Sheet name="Sheet1", rows=[["Name", "Class", "Score % ", "Score Actual", "Salary", "My vals", nil], ["Ben", "A", 0.0087, "98", "300", 0.0087, nil], ["Oskar", "A", 0.005600000000000001, "78", "500", 0.005600000000000001, nil], ["Jasmine", "B", 0.006999999999999999, "87", "350.2", 0.006999999999999999, nil]]] 

The 0.0087 should be 0.87

It appears that the division by 100 in the casting by format is not required?

Is this a Mac only issue or a general one?

Thanks, Ben

**Comment by woahdae** [comment]
Oh interesting, I can't say I remember the last time I used a percentage. Hmmm, I don't have the time to look up the xlsx spec at the moment, but this could be a bug.

**Comment by benhosken** [comment]
Ok thanks. That is enough at the moment as I'll "assume" it is a bug ad code around it for the moment. 
I'll also check on some other XLS versions and let you know if I find it is Mac only etc.
