### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by prosanes** [woahdae/simple_xlsx_reader#27]
I believe there is a memory leak. The test I did is describe below.
```
s = SimpleXlsxReader.open('big.xlsx')
s = nil
GC.start
```
The memory consuption was ~2,000MB before the open. With the file open, it went to ~3,400MB. After the garbage collector, it went to ~3,200MB

**Comment by woahdae** [comment]
This sounds like a common misconception about how Ruby handles system memory. It also looks like you are measuring virtual memory size, where you should probably measure resident set size (i.e. "real" memory).

Anyways, Ruby doesn't give memory back to the system. Ruby's garbage collector frees system-allocated memory for internal re-use, but does not release it back to the system. Anecdotally, for whatever reason, I've seen Ruby 2.3 appear to give a bit back to the system under some undetermined situation which is totally new behavior for Ruby that I don't yet understand (it might be something like Puma using some 2.3-specific copy-on-write/process fork strategy). In any case, process you describe should not be expected to release system memory.

Issue #25 addresses the real issue, that memory consumption is too high as a whole. It's an important topic, but not low-hanging fruit. Pull requests welcome ;-)

**Comment by prosanes** [comment]
Wow, sorry about that. And thank you for explaining it.
Bellow is the code that proves what @woahdae said
```
10.times { rss1 = GetProcessMem.new.mb; s = SimpleXlsxReader.open('big.xlsx'); s = nil; GC.start; rss2 = GetProcessMem.new.mb; puts "Diff: #{rss2 - rss1}mb. Total: #{rss2}" }
Diff: 290.75830078125mb. Total: 428.421875
Diff: 53.95703125mb. Total: 482.39453125
Diff: 24.03125mb. Total: 506.42578125
Diff: 1.60546875mb. Total: 508.03125
Diff: -1.41015625mb. Total: 506.62109375
Diff: 0.0mb. Total: 506.62109375
Diff: -0.0078125mb. Total: 506.61328125
Diff: 0.0mb. Total: 506.61328125
Diff: -0.04296875mb. Total: 506.5703125
Diff: -0.00390625mb. Total: 506.56640625
```
