### ISSUE TITLE
Use case-insensitive sheet matching

### ISSUE THREAD

**Issue by ruckus** [woahdae/simple_xlsx_reader#31]
Some XLSX creators create sheet names with a capital-S which causes the regex on:

https://github.com/woahdae/simple_xlsx_reader/blob/master/lib/simple_xlsx_reader.rb#L122

to fail. The solution is easy: just implement the `/i` regex flag like so:

```ruby
entry.name.match(/^xl.worksheets.sheet([0-9]*)\.xml$/i
```

I could submit a PR if you want, but its a one-character change. For now I monkey-patched it.

**Comment by woahdae** [comment]
I believe this was fixed in another PR, and also in https://github.com/woahdae/simple_xlsx_reader/tree/2.0.0-pre.
