### ISSUE TITLE
TypeError: {:keyword_init=>true} is not a symbol in new 2.0.0-pre

### ISSUE THREAD

**Issue by people-devs** [woahdae/simple_xlsx_reader#36]
simple_xlsx_reader/loader.rb:22:in `new': {:keyword_init=>true} is not a symbol (TypeError)

this is on ruby 2.4.5 - perhaps you can make the gem compatible for the upgrade-challenged? 
something along these lines might help? https://github.com/alexford/twilito/issues/4

_Originally posted by @woahdae in https://github.com/woahdae/simple_xlsx_reader/issues/25#issuecomment-1133430399_

**Comment by woahdae** [comment]
I have to be honest, I'm not super stoked to support 2.4.5, but I'd consider a PR?

**Comment by woahdae** [comment]
We now rely on Ruby 2.6 `exception: false` feature in casting with `Integer` and `Float`, so that's the minimum version unless a fork of the project is made that uses (slower) exception handling instead.
