### ISSUE TITLE
Special and long words, such as German words, are not supported in the new version. 

### ISSUE THREAD

**Issue by kia-kamangar** [woahdae/simple_xlsx_reader#39]
In the **1.0.5** version, we could read the column that has an object value, but in the new version, we can't read them.

**Comment by kia-kamangar** [comment]
In the newest version (2.0.0), I checked my RSpec test that includes a long text with `{{ }}` but after I got my excel in the test I lose some part of the expected text.

**Comment by kia-kamangar** [comment]
my xlsx_helper that included in the RSpec configuration

```ruby
module XlsxHelpers
  def xlsx_from_response(response)
    file = Tempfile.new('response')
    file.binmode
    file.write(response.body)
    file.rewind

    SimpleXlsxReader.open(file)
  end
end

RSpec.configure do |config|
  config.include XlsxHelpers
end
```
It's my RSpec test file

```ruby
context 'when XLSX is requested' do
  subject(:result) { xlsx_from_response(response) }

  before { get :index, format: :xlsx }

  let(:item) { create(:item) }
  let(:headers) { result.sheets.first.rows.slurp.first }
  let(:contents) { result.sheets.first.rows.slurp.last }
  let(:keys_and_titles) { %w(id item_attribute_1 item_attribute_2) }
  let(:expected_excel_contents) do
    [
      item.id,
      item.attribute_1,
      item.attribute_2,
    ]
  end

  it 'returns correct headers and contents' do
    expect(headers).to eq(keys_and_titles)
    expect(contents).to eq(expected_excel_contents)
  end
end
```

item.attribute_2 is the long text that includes `{{ }}`  but I get half of them like below screenshots

`item.attribute_2:` that was added to the excel sheet 
(it's start with the `{% c_gender person-gender-salute,Men,Women %}`)
![Screenshot from 2022-12-15 12-25-40](https://user-images.githubusercontent.com/53176737/207828196-1d83755b-5c90-475c-8d0d-953fed50461c.png)

item.attribute_2 after getting via `simple_xlsx_reader` that start with half of `{{dpo-description-en-may}}`
![Screenshot from 2022-12-15 12-26-20](https://user-images.githubusercontent.com/53176737/207828431-bf510bcc-29d8-4cc1-959d-8efbcc1e1941.png)

**Comment by kia-kamangar** [comment]
I try to open an xlsx file with SimpleXlsxReader and I got the below result

<img width="421" alt="Screenshot 2023-02-13 at 19 21 53" src="https://user-images.githubusercontent.com/53176737/219060359-81604057-5c9d-414a-8b5f-723383580c70.png">

and after opening the above file with `simple_xlsx_reader`  all letters before the German word was removed

<img width="863" alt="Screenshot 2023-02-13 at 19 24 44" src="https://user-images.githubusercontent.com/53176737/219060832-d060af3e-edd1-4a88-b96c-d2c167a0a278.png">

**Comment by woahdae** [comment]
I've copied all the examples provided here into excel and ran them through simple_xlsx_reader, and they parse correctly.

Excel has lots of quirks, I'll need an actual excel file exhibiting the issue to be able to address it.

**Comment by kia-kamangar** [comment]
this is a file that I used in the above example.

[companies.xlsx](https://github.com/woahdae/simple_xlsx_reader/files/10889046/companies.xlsx)

**Comment by woahdae** [comment]
Thanks, that helped me find the issue. Fixed!
