### ISSUE TITLE
Should not treat all cells with the "Generic" style as strings

### ISSUE THREAD

**Issue by jrodrigosm** [woahdae/simple_xlsx_reader#40]
Hi!

I've realized that, when reading the contents of a cell, if the cell's type is missing and the cell's style is "Generic", the gem treats the cell's value as if it was a string. Line 874 in `test/simple_xlsx_reader_test.rb` says it all: `it "reads 'Generic' cells as strings" do`.

This is actually a problem: when reading a spreadsheet with numeric values that have no type and a "Generic" style, the gem does not convert them to numbers, but leaves them as strings. This happens, for example, if you create a spreadsheet (with just numbers and no formatting) in Google Sheets and download it as an .xlsx file. If you try to read the file with the gem, you'll see that all the numbers are read as if they were strings.

I have created a (currently failing) test to show the behavior: https://github.com/jrodrigosm/simple_xlsx_reader/tree/treat-typeless-cells-as-numbers-by-default . This is the diff:
```
diff --git a/test/simple_xlsx_reader_test.rb b/test/simple_xlsx_reader_test.rb
index 20724cd..cc159dc 100644
--- a/test/simple_xlsx_reader_test.rb
+++ b/test/simple_xlsx_reader_test.rb
@@ -818,6 +818,10 @@ describe SimpleXlsxReader do
                 <c r='I1' s='0'>
                   <v>GUI-made hyperlink</v>
                 </c>
+
+                <c r='J1' s='0'>
+                  <v>1</v>
+                </c>
               </row>
             </sheetData>
 
@@ -916,6 +920,10 @@ describe SimpleXlsxReader do
         )
       )
     end
+    
+    it "reads 'Generic' cells with numbers as numbers" do
+      _(@row[9]).must_equal 1
+    end
   end
 
   describe 'parsing documents with blank rows' do
```

I think the gem might be interpreting the "Generic" style incorrectly. According to the standard, if the cell's type is missing, it should be treated as a number by default (see section 18.18.11 of the ECMA-376 standard, and see also line 3918 in section A.2). The standard also says that a "Generic" format can perfectly be applied to numbers (section 18.8.30).

I think the gem's behavior should probably be tweaked so that, if a cell's type is missing (which means, by default, that it is a number), and its style is "Generic", the cell value is NOT parsed as a string, but as a number (Integer, Float) or a date.

Would you agree with this interpretation?

If so, would you accept a PR?

**Comment by woahdae** [comment]
Agree, seems like a misunderstanding on my part. Thanks!
