### ISSUE TITLE
disappear string for long text

### ISSUE THREAD

**Issue by chaoswith** [woahdae/simple_xlsx_reader#45]
original text
皮革制品 - 皮革制品需避免接触水分(雨水，水，汗液等)，油，湿气及阳光直射。佩戴及携带时，可能与其它色彩的产品摩擦引起移染，因此与其它产品(特别是 JEANS 等服装)接触时敬请注意。 - 若不小心弄湿，请立即除去水渍，将商品的损伤最小化。 - 天然皮革表面上的伤痕及斑点，并不是缺陷而是使用天然素材的证据。 - 根据素材特性，因使用会产生磨耗或掉色，此情况与产品的耐久性无关。 - 浅色材质，易发生被外部深色物体染色的可能性，使用时请多加注意。 丝巾、皮带及饰品没有专门可以维修的部分，请多加注意。

->

read by simple_xlsx_reader
请多加注意。 丝巾、皮带及饰品没有专门可以维修的部分，请多加注意。

how to fix?

**Comment by woahdae** [comment]
I wrote a test for this by putting the original text in a spreadsheet (using MS Excel 2021 for Mac), and I am able to read the original text out in a test.

Could you provide a simple spreadsheet that reproduces this issue, or ideally a failing test case (using a real excel file)?
